{% set name = "gspread-dataframe" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gspread-dataframe-{{ version }}.tar.gz
  sha256: 5ca5493478ecae49b833664a06bac8e17b5b4ed0bdf77f551c948f30545860e6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - gspread >=3.0.0
    - pandas >=0.24.0
    - six >=1.12.0

test:
  imports:
    - gspread_dataframe
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/robin900/gspread-dataframe
  summary: Read/write gspread worksheets using pandas DataFrames
  doc_url: https://pythonhosted.org/gspread-dataframe/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maresb
